<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah</name>
   <tag></tag>
   <elementGuidId>822a2e3c-9795-43c3-95e8-17d9358fbee7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-sm.btn-edit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Tambah&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c51910b-cb35-48ca-81bb-f10e5c509047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm btn-edit</value>
      <webElementGuid>a36c67d3-55f1-4002-a26e-2d80f3d79cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b6fc1780-0f21-437c-aeb8-a581584305fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah</value>
      <webElementGuid>131f19a5-bab8-4788-8ec9-92b0204d93d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblCari&quot;)/tbody[1]/tr[1]/td[@class=&quot;dtfc-fixed-start dtfc-fixed-left&quot;]/button[@class=&quot;btn btn-primary btn-sm btn-edit&quot;]</value>
      <webElementGuid>69c2baba-a923-4d07-8dfb-fa692855afdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>4b4a862f-eaee-48b7-9020-127cd1295948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblCari']/tbody/tr/td/button</value>
      <webElementGuid>3ed0846f-20b1-472e-84e1-a212a0176612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Pemeriksaan Terakhir'])[2]/following::button[1]</value>
      <webElementGuid>e2d17b3f-73ea-44e6-9422-9bf48b493787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tindakan'])[2]/following::button[1]</value>
      <webElementGuid>70ca73e8-3a24-4273-ae8d-a42adeebd3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAUD KB TK RUMAH KITA (tidak ada tagihan)'])[1]/preceding::button[1]</value>
      <webElementGuid>59716fd3-7873-4c8f-a1f1-a178048c23f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JL BUKIT CEMARA INDAH C1 / 11'])[1]/preceding::button[1]</value>
      <webElementGuid>9759b3b5-2ae5-446b-aa7c-0e067d546754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button</value>
      <webElementGuid>bcc76da5-d329-493d-a860-a40c5c1fa338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Tambah' or . = ' Tambah')]</value>
      <webElementGuid>99db24c1-f384-400a-9d6d-5f63019cd8f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
