<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Pemeriksaan_swalTglPeriksa</name>
   <tag></tag>
   <elementGuidId>2f5b4bf8-a030-4efe-9dcd-8e1ed43d322d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='swalTglPeriksa']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#swalTglPeriksa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan Tanggal Pemeriksaan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18d7b2be-1dd2-4f33-b983-905a538f784e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>26261946-533c-4e35-9480-ecf93d0e1bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d5f383c7-ff00-4e1b-ab4c-51f0ebc68180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swalTglPeriksa</value>
      <webElementGuid>ae0cfc0f-f5cf-4c17-9075-90224f997285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>swalTglPeriksa</value>
      <webElementGuid>d9c3f90a-9594-4cd9-89c5-b2abeca24164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Tanggal Pemeriksaan</value>
      <webElementGuid>6aa1e513-6267-4082-a4ea-52118d2ae44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12/09/2025</value>
      <webElementGuid>641df4dd-3b71-4f89-b7d6-010c8a101280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swalTglPeriksa&quot;)</value>
      <webElementGuid>ef569748-af70-4f1e-b1ba-d470079503fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='swalTglPeriksa']</value>
      <webElementGuid>9ff6fbe5-feac-4d2e-b290-2883124f0b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmUsermodal']/div[8]/div/input</value>
      <webElementGuid>ddf3bc31-2e39-4490-9320-19b9261def95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>5fa4c168-4d90-4e6c-adee-8f6a7bf53af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'swalTglPeriksa' and @name = 'swalTglPeriksa' and @placeholder = 'Masukkan Tanggal Pemeriksaan']</value>
      <webElementGuid>28edc811-02d1-4c42-83bf-819be245801a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
