<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login_RO</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>051a2c3c-bf67-4773-bb57-08985aa08d99</testSuiteGuid>
   <testCaseLink>
      <guid>c552997b-9756-4160-8b03-556fdc40b16a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Awasrik/Login/TC-001_Login_User_Valid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>GlobalVariable.userro</value>
         <variableId>ed99e854-ab97-444c-aedf-4adbc45c5d03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>GlobalVariable.passwordro</value>
         <variableId>fcb81cf2-f9ed-452e-8310-898bb66e3135</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
