<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login_Kacab</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>eb560102-0530-40d7-bfdd-33a0808055c1</testSuiteGuid>
   <testCaseLink>
      <guid>a74cddb1-0835-402c-9672-49f89d254e7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Awasrik/Login/TC-001_Login_User_Valid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>GlobalVariable.userkacab</value>
         <variableId>ed99e854-ab97-444c-aedf-4adbc45c5d03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>GlobalVariable.passwordkacab</value>
         <variableId>fcb81cf2-f9ed-452e-8310-898bb66e3135</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
